### ISSUE TITLE
License of the content itself

### ISSUE THREAD

**Issue by stefanwalther** [fusionpbx/open-source#54]
Hi,

can I freely re-use the content on this page, so the text you have written in this umbrella project?

Regards Stefan

**Comment by markjcrane** [comment]
fusionpbx/open-source is repository to track those contributing content such as the documentation and/or code for the project. FusionPBX itself is mostly under an MPL license but there is a few 3rd party libraries that have their own license. Such as boostrap, adminer, and others. If this doesn't answer you question please respond with additional details to your question.

**Comment by stefanwalther** [comment]
Thx.
